import {
  Award,
  CheckCircle2,
  ChevronDown,
  Circle,
  FolderEdit,
  Heart,
  HelpCircle,
  History,
  LogOut,
  MessageSquare,
  Radio,
  Shield,
  ShieldAlert,
  Sparkle,
  Sword,
  Trophy,
  Unlock,
  User2,
  Users,
  Youtube,
  Zap,
} from "lucide-react";

export const Icons = {
  sword: Sword,
  shield: Shield,
  shieldAlert: ShieldAlert,
  history: History,
  message: MessageSquare,
  youtube: Youtube,
  thunder: Zap,
  logout: LogOut,
  user: User2,
  edit: FolderEdit,
  downarrow: ChevronDown,
  unlock: Unlock,
  stream: Radio,
  heart: Heart,
  star: Sparkle,
  help: HelpCircle,
  circle: Circle,
  trophy: Trophy,
  users: Users,
  award: Award,
  checkmark: CheckCircle2,
};
