import {
  ChevronDown,
  FolderEdit,
  Heart,
  HelpCircle,
  History,
  LogOut,
  MessageSquare,
  Radio,
  Shield,
  ShieldAlert,
  Sparkle,
  Sword,
  Unlock,
  User2,
  Youtube,
  Zap,
} from "lucide-react";

export const Icons = {
  sword: Sword,
  shield: Shield,
  shieldAlert: ShieldAlert,
  history: History,
  message: MessageSquare,
  youtube: Youtube,
  thunder: Zap,
  logout: LogOut,
  user: User2,
  edit: FolderEdit,
  downarrow: ChevronDown,
  unlock: Unlock,
  stream: Radio,
  heart: Heart,
  star: Sparkle,
  help: HelpCircle,
};
